### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by KnuffelBeestje** [MillenniumEarl/YAM#54] opened 2020-12-06 17:49 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/22412324/101287928-9f0de280-37f3-11eb-9790-b3cda14119ef.png)

**First appearance:** 2.4.3 after updating it from 2.3.1.

**Comment by MillenniumEarl** [comment] 2020-12-07 09:05
Thanks for the feedback!

- Were you doing something particular when the error appeared?
- What screen were you on? (main/update/etc...)
- In case you can share the two log files (main.log and renderer.log) that you find in **settings > open log files folder**

**Comment by KnuffelBeestje** [comment] 2020-12-07 10:14
- I booted the application and the error appeared out of nowhere.
- Main screen
- [Log file](https://gist.github.com/KnuffelBeestje/3a1cf8c4e2048fe9473a619a1263a4f7) & [Renderer File](https://gist.github.com/KnuffelBeestje/701467b58b13452b5f5a8b606e3446fc)

**Comment by MillenniumEarl** [comment] 2020-12-07 15:49
Thanks!
Does the error reappear when you change the page? maybe it happens on a specific page?

May I ask if you can also attach the three databases with the `.db` extension that you find in (_log folder > **upper folder** > appcache_)?
Maybe with the same data I can reproduce the problem on my PC.

**Probable cause:**
The only thing that has to do with time (and that can give this kind of error) is the string-to-date conversion of the last game update (or main thread post). If that's what I think, some game has an incorrect string format and when the application tries to convert it this error occurs.

**Comment by KnuffelBeestje** [comment] 2020-12-07 17:56
Here you go: [https://cdn.knuffelbeestje.com/YAM-Appcache.rar](https://cdn.knuffelbeestje.com/YAM-Appcache.rar)

**Comment by MillenniumEarl** [comment] 2020-12-07 20:23
Fixed, the issue was due to a recommended game with a non-ISO 8601 date.
Patched in #61, closing

**Closed by MillenniumEarl** 2020-12-07 20:23 UTC
Labels: bug
